# Gitea Actions workflow for building and deploying documentation

name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme myst-parser
    
    - name: Build documentation
      run: |
        cd docs
        make html
    
    - name: Deploy to Gitea Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # For Gitea, you may need to configure pages deployment
        # This depends on your Gitea instance configuration
        mkdir -p public
        cp -r docs/build/html/* public/
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/build/html
